/** @file
  GUIDs auto-generated for EFI test assertion.

  Copyright (c) 2006 - 2017, Intel Corporation. All rights reserved.<BR>
  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

**/

#include <Uefi.h>
#include "Guid.h"


EFI_GUID gArchTimerConsistencyTestAssertionGuid001 = EFI_TEST_ARCHTIMERCONSISTENCYTEST_ASSERTION_001_GUID;

EFI_GUID gArchTimerConsistencyTestAssertionGuid002 = EFI_TEST_ARCHTIMERCONSISTENCYTEST_ASSERTION_002_GUID;

EFI_GUID gArchTimerConsistencyTestAssertionGuid003 = EFI_TEST_ARCHTIMERCONSISTENCYTEST_ASSERTION_003_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid001 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_001_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid002 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_002_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid003 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_003_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid004 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_004_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid005 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_005_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid006 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_006_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid007 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_007_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid008 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_008_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid009 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_009_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid010 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_010_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid011 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_011_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid012 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_012_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid013 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_013_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid014 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_014_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid015 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_015_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid016 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_016_GUID;

EFI_GUID gArchTimerInterfaceTestAssertionGuid017 = EFI_TEST_ARCHTIMERINTERFACETEST_ASSERTION_017_GUID;

